language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t pressureandtime/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true pressureandtime/react-test npm test
after_success:
  - docker build  -t pressureandtime/multi-client ./client
  - docker build  -t pressureandtime/multi-nginx ./nginx
  - docker build  -t pressureandtime/multi-server ./server
  - docker build  -t pressureandtime/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pressureandtime/multi-client
  - docker push pressureandtime/multi-nginx
  - docker push pressureandtime/multi-server
  - docker push pressureandtime/multi-worker



deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-276076754845
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
